{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grainops.fullname" . }}-redis
  labels:
    {{- include "grainops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "grainops.selector" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grainops.fullname" . }}-redis
  labels:
    {{- include "grainops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "grainops.selector" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "grainops.selector" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 1000
        {{- include "grainops.podSecurityContext" . | nindent 8 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", {{ .Values.redis.maxmemory | quote }}, "--maxmemory-policy", "allkeys-lru"]
          securityContext:
            {{- include "grainops.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: redis
            periodSeconds: 20
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
